import type { Generated, Insertable, Selectable, Updateable } from "kysely";

export interface Database {
  todos: TodosTable;
}

export interface TodosTable {
  // Columns that are generated by the database should be marked
  // using the `Generated` type.
  id: Generated<number>;

  user_id: Generated<string>;

  task: string;

  inserted_at: Generated<Date>;
}

// You can use these types in your application code
export type Todo = Selectable<TodosTable>;
// export type NewUser = Insertable<UsersTable>;
// export type UserUpdate = Updateable<UsersTable>;
